---
- name: Ensure docker users are added to the docker group.
  shell:
    cmd: "usermod -aG docker {{ item }}"
    args:
      executable: /usr/bin/bash
  with_items: "{{ docker_users }}"
  become: yes
