---
- name: Ensure docker users are added to the docker group.
  ansible.builtin.shell: "usermod -aG docker {{ item }}"
  args:
    executable: /bin/bash
  with_items: "{{ docker_users }}"
  become: yes
  
- name: Ensure docker group is activated.
  ansible.builtin.shell: "newgrp docker"
  args:
    executable: /bin/bash
  become: yes
